---
title: "Team registration and proposal"
output: github_document
---

### Group members (names and UNIs)
* Eunsuh Cho (ec3663)
* Victoria Mello (vsm2118)
* Nhu Nguyen (nn2477)
* Victoria Schliep (vas2145)
* Maggie Watson (mgw2144)

### Tentative project title
Do the rats run this city or do we?

### Project motivation
Rats have continuously posed a health and infrastructure risk to NYC and its residents, and despite numerous attempts by the city to curb the pervasive nature of the animals, rats are seen daily and have cemented themselves as a part of NYC culture. We are aiming to analyze the relationship between rat sightings in NYC and features of NYC, including population density, income level, and stray cat density.

### Intended final products
-   Dashboards of the following: 
  - Rat sighting vs population size by neighborhood
  - Rat sighting vs income level by neighborhood
  - Rat density map over years
  - Rat vs cat density by neighborhood

### Anticipated data sources
-   NYC OpenData - Rat Sightings
-   NYC 2020 Census Data
-   NYC Feral Cat Colony Data (if available, working on obtaining)

### Planned Analyses
- General rat sighting analyses 
  - Change in number of rat sightings by year 
  - Change in average number of rat sightings per month 
  - Analysis of rats by neighborhood 

- Analysis of neighborhood rat sightings compared to income level 
  - Compare income level dataset with rat sighting dataset to assess income to rat 
  - Compare borough average income to average annual rat sightings 
  - Design a map comparing neighborhood imcome to rat sightings with latitude and longitude data 

- Analysis of population density to rat sightings 
  - Population density compared to rat sighting density by neighborhood
  - Borough population density to average annual rat sightings 

- Tentative feral cat colony to rat sighting analysis 
  - Distribution of feral cat colonies to rat insights 
  - Aim is to see if a correlation exists between higher cat colony density and lower rat sightings 
  - Assess the relationship between density of stray cats in neighborhoods and number of rat sightings


### Visualizations

- Mapping latitude/longitude coordinates in a leaflet map to show rat sighting distributions across brough(s) or in combination with outside factors (neighborhood level data?) 
- Box plots to compare monthly and annual averages in analyses for rat sightings compared to borough, population, SES, etc. 
- Bar plots to compare avg annual rat sightings by borough 
- Density plots to show rat sighting and population density (Across all boroughs) 

### Coding challenges
- Data tidying across datasets, years, neighborhods/boroughs, etc
- Ensuring all neighborhoods and zip codes are coded correctly 
- Plot reproducibility and readability 
- Keeping datasets tidy through the whole process and careful merging
  - Determining what variables to merge by 
  - May need to exclude the year 2023 from analysis depending on what is being analyzed as the data for the year is not yet complete, which may skew results 

### Proposed Timeline
- Meeting Nov 13-17th 
- Nov 17 - 21: clean data and conduct analysis
- Nov 27 - Dec 2: develop report, webpage, and screencast
- Dec 2 - Dec 9: refine and troubleshoot; peer assessments; submission

